user_pref("print.print_bgcolor", true);
user_pref("print.print_bgimages", true);
user_pref("print.print_duplex", 0);
user_pref("print.print_evenpages", true);
user_pref("print.print_footerleft", "");
user_pref("print.print_footerright", "");
user_pref("print.print_headerleft", "");
user_pref("print.print_headerright", "");
user_pref("print.print_oddpages", true);
user_pref("print.print_orientation", 0);
user_pref("print.print_page_delay", 50);
user_pref("print.print_paper_data", 0);
user_pref("print.print_paper_height", " 11.00");
user_pref("print.print_paper_size_unit", 0);
user_pref("print.print_paper_width", "  8.50");
user_pref("print.print_scaling", "  1.00");
user_pref("print.print_shrink_to_fit", true);
user_pref("print.print_to_file", false);
user_pref("print.print_unwriteable_margin_bottom", 0);
user_pref("print.print_unwriteable_margin_left", 0);
user_pref("print.print_unwriteable_margin_right", 0);
user_pref("print.print_unwriteable_margin_top", 0);
user_pref("print_printer", "Print to File");
user_pref("browser.preferences.defaultPerformanceSettings.enabled", false);
user_pref("dom.ipc.processCount", 1);
user_pref("layers.acceleration.disabled", true);
