user_pref("print.printer_Print_to_File.print_bgcolor", true);
user_pref("print.printer_Print_to_File.print_bgimages", true);
user_pref("print.printer_Print_to_File.print_duplex", 0);
user_pref("print.printer_Print_to_File.print_evenpages", true);
user_pref("print.printer_Print_to_File.print_footerleft", "");
user_pref("print.printer_Print_to_File.print_footerright", "&P");
user_pref("print.printer_Print_to_File.print_headerleft", "");
user_pref("print.printer_Print_to_File.print_headerright", "");
user_pref("print.printer_Print_to_File.print_oddpages", true);
user_pref("print.printer_Print_to_File.print_orientation", 0);
user_pref("print.printer_Print_to_File.print_page_delay", 50);
user_pref("print.printer_Print_to_File.print_paper_data", 0);
user_pref("print.printer_Print_to_File.print_paper_height", " 11.00");
user_pref("print.printer_Print_to_File.print_paper_size_unit", 0);
user_pref("print.printer_Print_to_File.print_paper_width", "  8.50");
user_pref("print.printer_Print_to_File.print_scaling", "  1.00");
user_pref("print.printer_Print_to_File.print_shrink_to_fit", true);
user_pref("print.printer_Print_to_File.print_to_file", false);
user_pref("print.printer_Print_to_File.print_unwriteable_margin_bottom", 56);
user_pref("print.printer_Print_to_File.print_unwriteable_margin_left", 25);
user_pref("print.printer_Print_to_File.print_unwriteable_margin_right", 25);
user_pref("print.printer_Print_to_File.print_unwriteable_margin_top", 25);
user_pref("print_printer", "Print to File");
user_pref("browser.preferences.defaultPerformanceSettings.enabled", false);
user_pref("dom.ipc.processCount", 1);
user_pref("layers.acceleration.disabled", true);
