[package]
name = "pdfserve"
version = "0.1.0"
authors = ["David Pascoe-Deslauriers <dpascoed@coldfrontlabs.ca>"]
edition = "2018"

[dependencies]
validator = "0.10.0"
uuid = { version = "0.8.1", features = ["v4"] }
rocket = { version = "0.4.4", features = ["tls"] }
